[theme]
primaryColor = "#f59e0b"
backgroundColor = "#0f172a"
secondaryBackgroundColor = "#1e293b"
textColor = "#cbd5e1"
font = "sans serif"

[server]
port = 8501
address = "0.0.0.0"
headless = true

[browser]
gatherUsageStats = false